# Generated by Django 5.1.1 on 2024-10-01 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Subscription", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="usersubscription",
            old_name="purchase_date",
            new_name="purchaseDate",
        ),
        migrations.RemoveField(
            model_name="usersubscription",
            name="expiry_date",
        ),
        migrations.AddField(
            model_name="usersubscription",
            name="expiryDate",
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name="subscriptionplan",
            name="description",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="subscriptionplan",
            name="name",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="subscriptionplan",
            name="price",
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
