# Generated by Django 5.1.1 on 2024-10-01 11:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "Subscription",
            "0002_rename_purchase_date_usersubscription_purchasedate_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name="usersubscription",
            old_name="expiryDate",
            new_name="expiry_date",
        ),
        migrations.RenameField(
            model_name="usersubscription",
            old_name="purchaseDate",
            new_name="purchase_date",
        ),
        migrations.CreateModel(
            name="Caretaker",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, null=True, unique=True
                    ),
                ),
                (
                    "phoneNumber",
                    models.CharField(blank=True, max_length=15, null=True, unique=True),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("male", "Male"),
                            ("female", "Female"),
                            ("other", "Other"),
                        ],
                        max_length=10,
                    ),
                ),
                ("age", models.IntegerField()),
                ("relationship", models.CharField(max_length=100)),
                ("average_time", models.CharField(max_length=100)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="caretakers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
