# Generated by Django 5.1.1 on 2024-09-27 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_user_groups_user_is_superuser_user_user_permissions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='blood_group',
            new_name='bloodGroup',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='disease_start_date',
            new_name='diseaseStartDate',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='phone_number',
            new_name='phoneNumber',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='phone_verified',
            new_name='phoneVerified',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='profile_complete',
            new_name='profileComplete',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='verification_code',
            new_name='verificationCode',
        ),
    ]
