# Generated by Django 5.1.1 on 2024-09-30 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("User", "0003_rename_blood_group_user_bloodgroup_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="phoneNumber",
            field=models.CharField(default="", max_length=15, unique=True),
        ),
    ]
