# Generated by Django 5.1.1 on 2024-09-30 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("User", "0004_alter_user_email_alter_user_phonenumber"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="phoneNumber",
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
    ]
