# Generated by Django 5.1.1 on 2024-09-30 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("User", "0005_alter_user_phonenumber"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="address",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
